// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// layout.js
import Link from 'next/link';
import './globals.css'; // Optional: Add your global styles here

export default function Layout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Simple E-Commerce Website</title>
        <meta name="description" content="A simple e-commerce website built with Next.js" />
      </head>
      <body>
        <header>
          <nav>
            <Link href="/">Home</Link>
            <Link href="/products">Products</Link>
            <Link href="/about">About Us</Link>
          </nav>
        </header>
        <main>{children}</main>
        <footer>
          <p>© 2024 Simple E-Commerce</p>
        </footer>
      </body>
    </html>
  );
}
